/* nighthq live dashboard — polls the unified backend and renders stat
   panels. No build step, no framework — matches the rest of the portfolio. */

const CONFIG = window.DASH_CONFIG || { BACKEND_URL: 'http://localhost:4100' };
const REFRESH_MS = 60000;
const PW_KEY = 'nighthq_dash_pw';

function $(sel) { return document.querySelector(sel); }

async function fetchJSON(path, opts = {}) {
  const pw = sessionStorage.getItem(PW_KEY);
  const res = await fetch(`${CONFIG.BACKEND_URL}${path}`, {
    ...opts,
    headers: { ...(opts.headers || {}), ...(pw ? { 'x-dashboard-password': pw } : {}) },
  });
  if (res.status === 401) { showAuthGate(); throw new Error('Unauthorized'); }
  if (!res.ok) throw new Error(`${path} → ${res.status}`);
  return res.json();
}

// ── password gate ────────────────────────────────────────────────────────
function showAuthGate() {
  const gate = document.getElementById('auth-gate');
  const content = document.getElementById('dashboard-content');
  if (gate) gate.style.display = 'flex';
  if (content) content.style.display = 'none';
}

function hideAuthGate() {
  const gate = document.getElementById('auth-gate');
  const content = document.getElementById('dashboard-content');
  if (gate) gate.style.display = 'none';
  if (content) content.style.display = 'block';
}

async function checkPassword(password) {
  const res = await fetch(`${CONFIG.BACKEND_URL}/api/auth/check`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ password }),
  });
  return res.ok;
}

async function initAuth() {
  const stored = sessionStorage.getItem(PW_KEY);
  if (stored && await checkPassword(stored)) {
    hideAuthGate();
    startDashboard();
    return;
  }
  sessionStorage.removeItem(PW_KEY);
  showAuthGate();

  const submit = document.getElementById('auth-submit');
  const input  = document.getElementById('auth-input');
  const error  = document.getElementById('auth-error');
  if (!submit || !input) return;

  const attempt = async () => {
    const ok = await checkPassword(input.value);
    if (ok) {
      sessionStorage.setItem(PW_KEY, input.value);
      error.style.display = 'none';
      hideAuthGate();
      startDashboard();
    } else {
      error.style.display = 'block';
    }
  };
  submit.addEventListener('click', attempt);
  input.addEventListener('keydown', e => { if (e.key === 'Enter') attempt(); });
}

function fmtMoney(cents, currency = 'USD') {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format((cents || 0) / 100);
}

function fmtNum(n) {
  return new Intl.NumberFormat('en-US').format(n || 0);
}

function badge(source) {
  return source === 'live'
    ? `<span class="badge live">Live</span>`
    : `<span class="badge mock">Mock</span>`;
}

function sparkline(points, valueKey) {
  const values = points.map(p => p[valueKey]);
  const max = Math.max(...values, 1);
  const min = Math.min(...values, 0);
  const range = max - min || 1;
  const w = 280, h = 40;
  const step = w / Math.max(points.length - 1, 1);
  const coords = values.map((v, i) => {
    const x = i * step;
    const y = h - ((v - min) / range) * h;
    return [x, y];
  });
  const line = coords.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  const fill = `${line} L${w},${h} L0,${h} Z`;
  return `<svg class="sparkline" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">
    <path class="fill" d="${fill}"></path>
    <path d="${line}"></path>
  </svg>`;
}

function setHTML(id, html) {
  const el = document.getElementById(id);
  if (el) el.innerHTML = html;
}

async function loadConnections() {
  try {
    const d = await fetchJSON('/api/connections');
    const tiles = d.services.map(s => `
      <div class="conn-tile">
        <span class="conn-dot ${s.status}"></span>
        <div>
          <div class="conn-name">${s.name}</div>
          <div class="conn-detail">${s.status} · ${s.detail}</div>
        </div>
      </div>
    `).join('');
    setHTML('connections-panel', `
      <div class="panel-head"><div class="panel-title">Connected Properties</div></div>
      <div class="conn-grid">${tiles}</div>
    `);
  } catch (e) {
    setHTML('connections-panel', `<div class="err">Connection status unavailable.</div>`);
  }
}

async function loadInsight() {
  try {
    const data = await fetchJSON('/api/insights');
    setHTML('insight-panel', `
      <div class="insight-banner">
        <div class="glyph">AI</div>
        <div>
          <p>${data.insight}</p>
          <div class="meta">${data.generatedWith === 'claude' ? 'Generated by Claude' : 'Fallback summary'} · refreshes every 10 min</div>
        </div>
      </div>
    `);
  } catch (e) {
    setHTML('insight-panel', `<div class="err">Insight unavailable — backend unreachable.</div>`);
  }
}

async function loadPurchases() {
  try {
    const d = await fetchJSON('/api/stats/purchases');
    setHTML('purchases-panel', `
      <div class="panel-head">
        <div class="panel-title">Purchases — 2AM Store</div>
        ${badge(d.source)}
      </div>
      <div class="stat-grid">
        <div class="stat-tile">
          <div class="stat-label">Last 30 Days</div>
          <div class="stat-value">${fmtMoney(d.last30DaysRevenueCents, d.currency)}</div>
          <div class="stat-sub">${fmtNum(d.last30DaysOrderCount)} orders</div>
        </div>
        <div class="stat-tile">
          <div class="stat-label">Today</div>
          <div class="stat-value">${fmtMoney(d.todayRevenueCents, d.currency)}</div>
        </div>
        <div class="stat-tile" style="grid-column:span 2">
          <div class="stat-label">14-Day Trend</div>
          ${sparkline(d.dailyTrend, 'cents')}
        </div>
      </div>
      ${d.note ? `<div class="panel-note">${d.note}</div>` : ''}
    `);
  } catch (e) {
    setHTML('purchases-panel', `<div class="err">Purchase stats unavailable.</div>`);
  }
}

async function loadDownloads() {
  try {
    const d = await fetchJSON('/api/stats/downloads');
    const cards = d.apps.map(app => `
      <div class="stat-tile">
        <div class="stat-label">${app.app}</div>
        <div class="stat-value">${fmtNum(app.totalDownloads)}</div>
        <div class="stat-sub">${fmtNum(app.last30Days)} in last 30 days</div>
        ${sparkline(app.dailyTrend, 'count')}
      </div>
    `).join('');
    setHTML('downloads-panel', `
      <div class="panel-head">
        <div class="panel-title">App Downloads</div>
        ${badge(d.source)}
      </div>
      <div class="stat-grid">${cards}</div>
      ${d.note ? `<div class="panel-note">${d.note}</div>` : ''}
    `);
  } catch (e) {
    setHTML('downloads-panel', `<div class="err">Download stats unavailable.</div>`);
  }
}

async function loadLeaderboard() {
  try {
    const d = await fetchJSON('/api/stats/leaderboard/carspootz');
    const rows = (d.entries || []).slice(0, 8).map((e, i) => `
      <tr class="${i === 0 ? 'rank-1' : ''}">
        <td><span class="rank-pip ${i === 0 ? 'gold' : ''}">${e.rank ?? i + 1}</span></td>
        <td>@${e.handle}</td>
        <td>${fmtNum(e.spots ?? 0)}</td>
        <td>${fmtNum(e.xp ?? 0)}</td>
      </tr>
    `).join('') || `<tr><td colspan="4" class="skel">No entries yet.</td></tr>`;
    setHTML('leaderboard-panel', `
      <div class="panel-head">
        <div class="panel-title">carspootz Leaderboard</div>
        ${badge(d.source)}
      </div>
      <table class="board">
        <thead><tr><th>#</th><th>Handle</th><th>Spots</th><th>XP</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      ${d.note ? `<div class="panel-note">${d.note}</div>` : ''}
    `);
  } catch (e) {
    setHTML('leaderboard-panel', `<div class="err">Leaderboard unavailable.</div>`);
  }
}

async function loadWinner() {
  try {
    const d = await fetchJSON('/api/coupon/monthly-winner/carspootz');
    setHTML('winner-panel', `
      <div class="panel-head">
        <div class="panel-title">This Month's Winner — ${d.month}</div>
        <span class="badge live">@${d.winnerHandle}</span>
      </div>
      <div class="coupon">
        <div class="coupon-code">${d.code}</div>
        <div class="coupon-msg">${d.message}</div>
      </div>
      <div class="panel-note">Won with ${fmtNum(d.metricValue)} ${d.metricLabel} · leaderboard source: ${d.leaderboardSource} (${d.leaderboardPeriod})</div>
    `);
  } catch (e) {
    setHTML('winner-panel', `<div class="err">Winner data unavailable.</div>`);
  }
}

async function loadWinnersHistory() {
  try {
    const d = await fetchJSON('/api/coupon/winners');
    const rows = (d.winners || []).slice().reverse().map(w => `
      <div class="mini-row">
        <span class="k">${w.month} · @${w.winnerHandle}</span>
        <span class="v">${w.code}</span>
      </div>
    `).join('') || `<div class="skel">No winners recorded yet.</div>`;
    setHTML('history-panel', `
      <div class="panel-head"><div class="panel-title">Hall of Fame</div></div>
      ${rows}
    `);
  } catch (e) {
    setHTML('history-panel', `<div class="err">History unavailable.</div>`);
  }
}

async function loadEngagement() {
  try {
    const d = await fetchJSON('/api/stats/engagement/bettermade');
    const rows = d.modules.map(m => `
      <div class="mini-row">
        <span class="k">${m.module} — ${m.metric}</span>
        <span class="v">${fmtNum(m.last30Days)}</span>
      </div>
    `).join('');
    setHTML('engagement-panel', `
      <div class="panel-head">
        <div class="panel-title">Bettermade Engagement</div>
        ${badge(d.source)}
      </div>
      ${rows}
      ${d.note ? `<div class="panel-note">${d.note}</div>` : ''}
    `);
  } catch (e) {
    setHTML('engagement-panel', `<div class="err">Engagement stats unavailable.</div>`);
  }
}

function refreshAll() {
  loadConnections();
  loadInsight();
  loadPurchases();
  loadDownloads();
  loadLeaderboard();
  loadWinner();
  loadWinnersHistory();
  loadEngagement();
  const stamp = document.getElementById('last-updated');
  if (stamp) stamp.textContent = `Last updated ${new Date().toLocaleTimeString()}`;
}

function startDashboard() {
  refreshAll();
  setInterval(refreshAll, REFRESH_MS);
}

document.addEventListener('DOMContentLoaded', initAuth);
